[package]
name = "dijkstra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graph_representations = { path = "../graph_representations" }
updatable_heap = { path = "../updatable_heap" }
